# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 06:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='custom_sql',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sql_name', models.CharField(help_text='查询名称', max_length=100, unique=True, verbose_name='查询名称')),
                ('sql_conten', models.TextField(help_text='查询语句', max_length=1500, verbose_name='SQL模板')),
                ('sql_para', models.TextField(blank=True, help_text='查询参数', max_length=5000, verbose_name='参数集')),
                ('sql_remark', models.TextField(blank=True, help_text='查询备注说明', verbose_name='备注说明')),
                ('creat_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', validators=['更', '新', '时', '间'])),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
        ),
        migrations.CreateModel(
            name='om_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(db_index=True, help_text='order id')),
                ('order_no', models.CharField(db_index=True, help_text='订单编号', max_length=25)),
                ('order_type', models.IntegerField(help_text='订单类型 1:代购|2:自助购')),
                ('total_count', models.IntegerField(help_text='订单总数量,由订单详情表数量累计而得')),
                ('total_amount', models.IntegerField(help_text='订单总金额,由订单详情表金额累计而得')),
                ('total_freight', models.IntegerField(help_text='订单总运费,由订单详情表运费累计而得')),
                ('order_time', models.DateTimeField(db_index=True, help_text='下单时间')),
                ('order_status', models.IntegerField(db_index=True, help_text='订单状态')),
                ('order_remark', models.CharField(help_text='订单备注', max_length=500)),
                ('seller_id', models.IntegerField(help_text='卖点id')),
                ('seller_name', models.CharField(help_text='卖家名字', max_length=50)),
                ('user_id', models.IntegerField(db_index=True, help_text='用户id')),
                ('user_name', models.CharField(help_text='用户名', max_length=20)),
                ('purchaser_id', models.IntegerField(help_text='采购id')),
                ('purchaser_name', models.CharField(help_text='采购用户名', max_length=20)),
                ('order_source', models.IntegerField(help_text='订单来源,1:C端用户,2:B端用户')),
                ('cancel_type', models.IntegerField(help_text='订单取消类型， 1:用户取消，2:系统取消')),
                ('cancel_reason', models.CharField(help_text='订单取消原因', max_length=200)),
                ('shop_source', models.CharField(help_text='店铺来源， 例如TM、TB、JD等', max_length=20)),
                ('shop_id', models.IntegerField(help_text='店铺id')),
                ('shop_nick', models.CharField(help_text='店铺名称', max_length=50)),
                ('shop_link', models.CharField(help_text='店铺url', max_length=100)),
                ('platform', models.IntegerField(help_text='订单创建平台 1pc 2ios 3android 4代购助手(目前只支持chrome)')),
                ('language', models.IntegerField(help_text='用户下单语言')),
                ('promotion_id', models.IntegerField(help_text='促销id')),
                ('receive_type', models.IntegerField(help_text='接单类型 1:普通|2:特定金额|3:特殊用户|4:特殊店铺|5:未知平台|6:yupoo|7:1688')),
                ('urgent', models.IntegerField(help_text='是否加急订单')),
                ('pay_time', models.DateTimeField(db_index=True, help_text='支付时间')),
                ('delivery_id', models.IntegerField(help_text='运送方式id')),
                ('delivery_name', models.CharField(help_text='运送方式名', max_length=20)),
                ('express_no', models.CharField(help_text='发货快递号', max_length=45)),
                ('country', models.CharField(help_text='配送目的国家', max_length=32)),
                ('state', models.CharField(help_text='收货地址的州', max_length=150)),
                ('city', models.CharField(help_text='城市名称', max_length=150)),
                ('address', models.CharField(help_text='街道地址', max_length=500)),
                ('consignee', models.CharField(help_text='收货人名', max_length=100)),
                ('phone', models.CharField(help_text='收货人电话', max_length=100)),
                ('warehouse_id', models.IntegerField(help_text='仓库id')),
            ],
        ),
        migrations.CreateModel(
            name='um_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True, help_text='用户id')),
                ('user_name', models.CharField(help_text='用户名称', max_length=20)),
                ('reality_money', models.FloatField(help_text='可提款的金额,用户充值的金额')),
                ('virtual_money', models.FloatField(help_text='奖励金额,返款,不可提款')),
                ('freeze_money', models.FloatField(help_text='冻结金额,不可使用')),
                ('point', models.IntegerField(help_text='积分')),
                ('reg_ip', models.IntegerField(help_text='注册ip')),
                ('reg_location', models.CharField(help_text='注册国家来源', max_length=40)),
                ('reg_time', models.DateTimeField(help_text='注册时间')),
                ('last_login_time', models.DateTimeField(help_text='上次登录时间')),
                ('last_login_ip', models.IntegerField(help_text='上次登录ip')),
                ('reg_tag', models.CharField(help_text='注册渠道跟踪参数', max_length=25)),
                ('reg_country_code', models.CharField(help_text='注册国家编码', max_length=4)),
                ('reg_from', models.CharField(help_text='注册来源', max_length=25)),
                ('reg_platform', models.IntegerField(help_text='注册的终端：1pc，2ios，3android...')),
                ('language', models.IntegerField(help_text='语言')),
                ('email', models.CharField(help_text='邮箱', max_length=100)),
                ('is_valid', models.IntegerField(help_text='邮箱是否验证')),
                ('is_pro_account', models.IntegerField(help_text='是否付费会员')),
                ('sensitive_goods_user', models.IntegerField(help_text='是否敏感品用户')),
                ('warehouse_id', models.IntegerField(help_text='仓库id，1:深圳仓，2:香港仓，3:scb仓')),
                ('birthday', models.CharField(help_text='生日', max_length=32)),
                ('gender', models.IntegerField(help_text='性别')),
                ('growth', models.IntegerField(help_text='成长值')),
                ('first_shopping', models.IntegerField(help_text='是否第一次购物')),
                ('first_send', models.IntegerField(help_text='是否第一次寄送包裹')),
                ('first_show', models.IntegerField(help_text='是否第一次晒单')),
            ],
        ),
    ]
